set_property IOSTANDARD LVCMOS33 [get_ports SPI_M_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_M_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_M_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_M_0_ss_io]
set_property PACKAGE_PIN J1 [get_ports SPI_M_0_ss_io]
set_property PACKAGE_PIN G2 [get_ports SPI_M_0_sck_io]
set_property PACKAGE_PIN J2 [get_ports SPI_M_0_io1_io]
set_property PACKAGE_PIN L2 [get_ports SPI_M_0_io0_io]
set_property PACKAGE_PIN A14 [get_ports tx_mclk_0]
set_property PACKAGE_PIN B15 [get_ports tx_sclk_0]
set_property PACKAGE_PIN B16 [get_ports tx_sdout_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_lrck_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_mclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_sdin_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_lrck_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_mclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_sdout_0]

set_property PACKAGE_PIN A16 [get_ports tx_lrck_0]
set_property PACKAGE_PIN A17 [get_ports rx_lrck_0]
set_property PACKAGE_PIN A15 [get_ports rx_mclk_0]
set_property PACKAGE_PIN C15 [get_ports rx_sclk_0]
set_property PACKAGE_PIN C16 [get_ports rx_sdin_0]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/balance_controller_0_m_axis_TDATA[0]} {design_1_i/balance_controller_0_m_axis_TDATA[1]} {design_1_i/balance_controller_0_m_axis_TDATA[2]} {design_1_i/balance_controller_0_m_axis_TDATA[3]} {design_1_i/balance_controller_0_m_axis_TDATA[4]} {design_1_i/balance_controller_0_m_axis_TDATA[5]} {design_1_i/balance_controller_0_m_axis_TDATA[6]} {design_1_i/balance_controller_0_m_axis_TDATA[7]} {design_1_i/balance_controller_0_m_axis_TDATA[8]} {design_1_i/balance_controller_0_m_axis_TDATA[9]} {design_1_i/balance_controller_0_m_axis_TDATA[10]} {design_1_i/balance_controller_0_m_axis_TDATA[11]} {design_1_i/balance_controller_0_m_axis_TDATA[12]} {design_1_i/balance_controller_0_m_axis_TDATA[13]} {design_1_i/balance_controller_0_m_axis_TDATA[14]} {design_1_i/balance_controller_0_m_axis_TDATA[15]} {design_1_i/balance_controller_0_m_axis_TDATA[16]} {design_1_i/balance_controller_0_m_axis_TDATA[17]} {design_1_i/balance_controller_0_m_axis_TDATA[18]} {design_1_i/balance_controller_0_m_axis_TDATA[19]} {design_1_i/balance_controller_0_m_axis_TDATA[20]} {design_1_i/balance_controller_0_m_axis_TDATA[21]} {design_1_i/balance_controller_0_m_axis_TDATA[22]} {design_1_i/balance_controller_0_m_axis_TDATA[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/balance_controller_0_m_axis_TLAST]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
